root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./wserver"
  cmd = "make server"
  exclude_dir = ["cmd/web/node_modules", "internal/database", "tmp"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "templ", "ts"]
  include_file = []
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = false
  delay = 10

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[proxy]
  enabled = true
  proxy_port = 3030
  app_port = 3000
